# Refer https://github.com/#configuration for documentation

urls:
  - path: "https://rcheuma.github.io/stopify-landing-page/" "http://stopify-20210716113720334100000001.s3-website.eu-west-3.amazonaws.com"
    type: "get"
